### ISSUE TITLE
Java version 1.8 is not supported

### ISSUE THREAD

**Issue by wqq-java** [ECharts-Java/ECharts-Java#51]
Java version 1.8 is not supported

**Comment by incandescentxxc** [comment]
Thanks for the issue. Currently, ECharts-Java supports Java 16. We are trying to provide Java 8 support in our next release.

**Comment by IcePear-Jzx** [comment]
Fixed by #52 
Java 8 is supported by ECharts Java v1.0.3. Please update your pom.xml.
If the problem still exists, please provide more information. Thanks for your issue.
