### ISSUE TITLE
Why can't I access the official website  ‘https://echarts.icepear.org/’

### ISSUE THREAD

**Issue by hellolujian** [ECharts-Java/ECharts-Java#54]
When open the link https://echarts.icepear.org/  , it's blank

**Comment by IcePear-Jzx** [comment]
It looks good to me. Please check your network and VPN.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/39995043/172318441-554b7bd7-9873-4c89-92bc-3d52f51cdc67.png">
