### ISSUE TITLE
register custom TypeAdapters

### ISSUE THREAD

**Issue by jbaron** [ECharts-Java/ECharts-Java#57]
Would love a way to register Gson custom TypeAdapters so I can stick closer to my domain model for the data in the charts and don't require all types of transformations. Perhaps this is  already possible, but couldn't find it in the documentation. 

For example (I use Kotlin), Gson by default doesn't handle `Pair`, `Triple`, `Instant` and my own custom types.

BTW, I use the `engine.renderJsonOption(chart)`  before sending it to the browser.

**Comment by jbaron** [comment]
Right now using my own Json rendering of the `chart.option` object, which also works fine. So not a high priority feature request.

**Comment by IcePear-Jzx** [comment]
`EChartsSerializer` will support custom adapters in the next release. 

Example:

```java
    public void testCustomEChartsSerializer() {
        EChartsSerializer serializer = new EChartsSerializer(new CustomObjectAdapter());
        Object object = new CustomObject("name");
        JsonElement actual = serializer.toJsonTree(object);
        JsonElement expected = JsonParser.parseString("'name'");
        assertEquals(expected, actual);
    }

    class CustomObject {
        private String name;

        public CustomObject(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    class CustomObjectAdapter implements EChartsTypeAdapter<CustomObject> {
        public JsonElement serialize(CustomObject src, Type typeOfSrc, JsonSerializationContext context) {
            return context.serialize(src.getName());
        }

        public Type getType() {
            return CustomObject.class;
        }
    }
```

**Comment by jbaron** [comment]
Great,  then I can use the EChartsSerializer which is a bit cleaner then doing my own serialisation (since I noticed ECharts-Java also has some own Adapters for more advanced chart types)
