### ISSUE TITLE
Complex Encode option question

### ISSUE THREAD

**Issue by jbaron** [ECharts-Java/ECharts-Java#58]
I have now migrated around 60% of my charts to using the ECharts-Java library and have to say it works like a charm. I'm pleasantly surprised that even the more exotic options are exposed through the API, great work!!!

The part I'm current struggling is to get the more complex Encode to work. For example in a candle stick series I require this as output:

`
encode: {
         x: 0,
        y: [1, 4, 3, 2]
 }
`

But all examples I could find only have a single key and value. Is the above possible. The following (Kotlin syntax) doesn't compile because setValue doesn't support nested arrays.:

`
val encode1 = Encode().setItemName(arrayOf("x", "y")).setValue(arrayOf(0, arrayOf(1,4,3,2))

val series1 = CandlestickSeries()
            .setEncode(encode1)
`

Thanks in advance for any tips.

**Comment by IcePear-Jzx** [comment]
I'm glad you are using ECharts-Java and post great issues to help us improve!

As described in [Apache ECharts doc](https://echarts.apache.org/en/option.html#series-line.encode), `setX`, `setY`, `setRadius`, `setAngle`, `setLng`, `setLat` should be supported. This is our mistake. Will fix it recently.

Thanks for your issue!

**Comment by jbaron** [comment]
Thanks you for quick response. Seems that will make it possible to convert 95% of my existing string template solution to the ECharts-Java library :)

BYW, do you know if anyone is looking into supporting TreeMap charts (that is the remaining 5% in my case) ?

**Comment by IcePear-Jzx** [comment]
Feel free to create a separate issue for TreeMap. I think it's not difficult to support.

**Comment by IcePear-Jzx** [comment]
This fix will be available in the next release. Hopefully, this week.

**Comment by jbaron** [comment]
Thanks for the very quick fix 👍
