### ISSUE TITLE
支持本地下载图片？

### ISSUE THREAD

**Issue by dearMOMO** [ECharts-Java/ECharts-Java#84]
不通过html下面图表，直接通过后台生成图片

**Comment by xiaomaiyun** [comment]
https://github.com/ECharts-Java/ECharts-Java/issues/61

**Comment by xiaomaiyun** [comment]
可以参考这个
https://github.com/ECharts-Java/ECharts-Java/issues/61

**Comment by incandescentxxc** [comment]
https://github.com/ECharts-Java/Snapshot-PhantomJS
